version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

  deploy_ios:
    macos:
      xcode: "9.3.0"
    steps:
    working_directory: /Users/distiller/project
    environment:
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: yarn install
      - run: bundle install
      - run: bundle exec fastlane ios prepare_build
      - run: bundle exec fastlane ios beta

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_ios:
          requires:
            - build
