version: 2

references:
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: echo $CIRCLE_BUILD_NUM > build_number.txt
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  deploy_ios:
    macos:
      xcode: "9.3.0"
    steps:
    working_directory: /Users/distiller/project
    environment:
    shell: /bin/bash --login -o pipefail
    steps:
      - *restore_repo
      - run: bundle install
      - run: bundle exec fastlane ios prepare_build
      - run: bundle exec fastlane ios beta build_number:$(cat build_number.txt)


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_ios:
          requires:
            - build
