version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    working_directory: ~/project
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

      - run: echo $CIRCLE_BUILD_NUM > build_number.txt
      - persist_to_workspace:
          root: .
          paths:
            - build_number.txt
            - node_modules

  deploy_ios:
    macos:
      xcode: "10.0.0"
    steps:
    working_directory: /Users/distiller/project
    environment:
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn add fsevents
      - run: cd node_modules/react-native && exec ./scripts/ios-install-third-party.sh
      - run: bundle install
      - run: bundle exec fastlane ios beta build_number:$(cat build_number.txt)


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_ios:
          requires:
            - build
